/**
 * German titles and keywords of the guides, for the search only. Generated together with the article
 * table in src/data/v4Insights.ts by `node gen-v4-insights.mjs`. The hub loads this file when someone
 * starts typing, so the first page load does not carry it.
 */
export type SearchEntry = { titleDe: string; terms: string };

export type SearchIndex = Readonly<Record<string, SearchEntry>>;

export const SEARCH_INDEX: SearchIndex = {
  "ultimate-guide-local-seo": { titleDe: "Local SEO: Der ultimative Leitfaden für lokale Unternehmen 2026", terms: "local seo, local seo guide, lokale suchmaschinenoptimierung, local seo strategie, google business profil" },
  "kostenloses-seo-guide": { titleDe: "Kostenloses SEO: Der ultimative Guide für Einsteiger 2026", terms: "kostenloses seo, seo kostenlos, gratis seo tools, seo für anfänger, local seo kostenlos" },
  "local-seo-keywords-finden": { titleDe: "Local SEO Keywords finden: Der komplette Keyword-Recherche Guide 2026", terms: "local seo keywords, keyword research, local keywords" },
  "google-maps-ranking-verbessern": { titleDe: "Google Maps Ranking verbessern: 7-Schritte-Aktionsplan 2026", terms: "google maps ranking verbessern, maps ranking steigern, google maps optimierung anleitung" },
  "google-bewertungen-bekommen": { titleDe: "Google Bewertungen bekommen: 7 bewährte Strategien", terms: "google reviews, get reviews, customer reviews" },
  "local-seo-fuer-restaurants": { titleDe: "Local SEO für Restaurants: Mehr Gäste durch Google", terms: "restaurant seo, local seo restaurant, gastro marketing" },
  "google-my-business-optimieren": { titleDe: "Google My Business optimieren: Schritt-für-Schritt Anleitung", terms: "google my business, gmb optimize, google business profile" },
  "lokale-suchmaschinenoptimierung-2026": { titleDe: "Lokale Suchmaschinenoptimierung 2026: Was wirklich funktioniert", terms: "local seo, search engine optimization, local seo 2026" },
  "nap-konsistenz-local-seo": { titleDe: "NAP-Konsistenz: Warum einheitliche Daten dein Ranking boosten", terms: "nap consistency, citations, business directories, local seo" },
  "local-seo-handwerker": { titleDe: "Local SEO für Handwerker: Mehr Aufträge durch Google", terms: "contractor seo, local seo contractors, contractor marketing" },
  "local-seo-audit-checkliste": { titleDe: "Local SEO Audit: Ist-Analyse mit 50+ Diagnose-Punkten & Scoring", terms: "local seo audit, seo diagnose, local seo analyse, seo scoring" },
  "local-seo-schweiz": { titleDe: "Local SEO Schweiz: Der komplette Leitfaden für KMUs", terms: "local seo schweiz, schweizer seo, kmu marketing, google business schweiz, lokales marketing schweiz" },
  "local-seo-zuerich": { titleDe: "Local SEO Zürich: So dominierst du den Zürcher Markt", terms: "local seo zürich, seo zürich, google ranking zürich, marketing zürich, unternehmen zürich" },
  "local-seo-muenchen": { titleDe: "Local SEO München: Der Guide für bayerische Unternehmen", terms: "local seo münchen, seo münchen, google ranking münchen, marketing münchen, bayerische unternehmen" },
  "local-seo-aerzte-praxen": { titleDe: "Local SEO für Ärzte & Praxen: Patientengewinnung durch Google", terms: "arzt seo, praxis marketing, local seo ärzte, patientengewinnung, jameda" },
  "local-seo-anwaelte-kanzleien": { titleDe: "Local SEO für Anwälte & Kanzleien: Mandanten durch Google gewinnen", terms: "anwalt seo, kanzlei marketing, local seo anwälte, mandantengewinnung, anwalt.de" },
  "local-seo-hotels": { titleDe: "Local SEO für Hotels & Unterkünfte: Direktbuchungen steigern", terms: "hotel seo, direktbuchungen, local seo hotels, google hotel ads, booking alternative" },
  "local-seo-fitness": { titleDe: "Local SEO für Fitnessstudios & Personal Trainer", terms: "fitnessstudio seo, personal trainer marketing, local seo fitness, mitgliedergewinnung" },
  "schema-markup-local-seo": { titleDe: "Schema Markup für Local SEO: Der Implementierungsguide", terms: "schema markup, strukturierte daten, local business schema, rich snippets, json-ld" },
  "google-maps-seo-ranking-faktoren": { titleDe: "Google Maps SEO 2026: Alle 20 Ranking-Signale mit Gewichtung", terms: "google maps ranking signale, ranking faktoren gewichtung, local pack signale, maps seo 2026, proximity relevance prominence gewichtung" },
  "google-maps-spam-erkennen": { titleDe: "Google Maps Spam erkennen & melden: Der komplette Guide", terms: "google maps spam, spam melden, fake bewertungen, keyword stuffing, google business spam" },
  "google-maps-konkurrenzanalyse": { titleDe: "Google Maps Konkurrenzanalyse: So analysierst du Top-Rankings", terms: "konkurrenzanalyse, competitor analysis, google maps, local pack, ranking analyse" },
  "entity-seo-guide": { titleDe: "Entity SEO: Wie Suchmaschinen Entitäten verstehen & nutzen", terms: "entity seo, knowledge graph, schema markup, sameas, structured data" },
  "semantic-seo-topical-authority": { titleDe: "Semantic SEO & Topical Authority: Der Komplettguide", terms: "semantic seo, topical authority, topic cluster, pillar page, themenautorität" },
  "google-maps-audit-template": { titleDe: "Google Maps Audit Template: Vollständige Checkliste mit 75+ Punkten", terms: "google maps audit, maps audit template, local seo audit, gbp audit, google maps checkliste" },
  "citation-tracking-template": { titleDe: "Citation Tracking Spreadsheet Template: Alle Verzeichnisse im Griff", terms: "citation tracking, citation spreadsheet, nap tracking, verzeichnis tracking, citation audit" },
  "local-keyword-research-template": { titleDe: "Local Keyword Research Template: Systematische Keyword-Recherche für lokale Unternehmen", terms: "keyword recherche, keyword research template, lokale keywords, keyword mapping, keyword spreadsheet" },
  "local-seo-monthly-checklist": { titleDe: "Local SEO Monthly Checklist: Die monatliche Routine für Top-Rankings", terms: "monthly checklist, monatliche checkliste, local seo routine, local seo pflege, seo maintenance" },
  "ai-visibility-checklist": { titleDe: "AI Visibility Checklist: Ist deine Website bereit für AI-Suche?", terms: "ai visibility, ai sichtbarkeit, ai checklist, ai overviews optimierung, llm optimierung" },
  "google-maps-ranking-tracker": { titleDe: "Google Maps Ranking Tracker: So trackst du deine lokalen Rankings", terms: "ranking tracker, google maps ranking, local rank tracking, grid tracking, geo grid" },
  "local-seo-strategy-planner": { titleDe: "Local SEO Strategy Planner: 7-Phasen-Aufgabenplan mit Budget & Checkliste", terms: "local seo aufgabenplan, seo strategy planner, seo aufgaben checkliste, local seo budget planung, seo phasen plan" },
  "local-seo-roadmap-90-tage": { titleDe: "Local SEO Wochenplan: 12-Wochen-Timeline mit Gantt-Diagramm & KPI-Meilensteinen", terms: "local seo wochenplan, 12 wochen timeline, seo gantt diagramm, local seo meilensteine, seo kpi tracking" },
  "local-link-building": { titleDe: "Local Link Building: Backlinks für lokale Unternehmen aufbauen", terms: "local link building, lokale backlinks, linkaufbau, backlink strategie, local authority" },
  "negative-google-bewertungen": { titleDe: "Negative Google Bewertungen: So reagierst du professionell", terms: "negative bewertungen, bewertungen beantworten, reputation management, schlechte bewertung, bewertung löschen" },
  "local-content-marketing": { titleDe: "Local Content Marketing: Content-Strategie für lokale Unternehmen", terms: "local content, content marketing, lokaler content, stadtteil seiten, lokale guides" },
  "local-seo-fehler": { titleDe: "Local SEO Fehler: 15 Gründe warum du nicht gefunden wirst", terms: "local seo fehler, seo probleme, nicht gefunden werden, seo diagnose, ranking probleme" },
  "local-seo-doener-kebab-imbiss": { titleDe: "Local SEO für Döner & Kebab-Imbisse: Der ultimative Marketing-Guide 2026", terms: "döner seo, kebab marketing, imbiss google, döner laden mehr kunden, döner bewertungen" },
  "local-seo-friseursalon-beauty": { titleDe: "Local SEO für Friseursalons & Beauty-Studios: Der ultimative Guide mit Buchungsintegration 2026", terms: "friseur seo, beauty marketing, friseursalon google, kosmetikstudio marketing, friseur mehr kunden" },
  "local-seo-immobilienmakler": { titleDe: "Local SEO für Immobilienmakler: Objektanfragen durch Google", terms: "immobilienmakler seo, makler marketing, local seo immobilien, objektanfragen" },
  "local-seo-steuerberater": { titleDe: "Local SEO für Steuerberater & Buchhalter: Mandanten gewinnen", terms: "steuerberater seo, buchhalter marketing, local seo steuerberater, mandantengewinnung" },
  "local-seo-autowerkstatt": { titleDe: "Local SEO für Autowerkstätten & KFZ-Betriebe", terms: "autowerkstatt seo, kfz marketing, local seo werkstatt, autohaus seo" },
  "local-seo-tierarzt": { titleDe: "Local SEO für Tierärzte & Tierpraxen", terms: "tierarzt seo, tierpraxis marketing, local seo tierarzt, veterinär marketing" },
  "local-seo-fotograf": { titleDe: "Local SEO für Fotografen: Mehr Buchungen durch Google", terms: "fotograf seo, fotografen marketing, local seo fotograf, hochzeitsfotograf seo" },
  "local-seo-yoga-studios": { titleDe: "Local SEO für Yoga-Studios & Pilates", terms: "yoga studio seo, pilates marketing, local seo yoga, wellness studio seo" },
  "local-seo-tattoo-studios": { titleDe: "Local SEO für Tattoo-Studios & Piercing", terms: "tattoo studio seo, piercing marketing, local seo tattoo, tattoo künstler seo" },
  "local-seo-apotheken": { titleDe: "Local SEO für Apotheken: Lokale Gesundheitsversorgung", terms: "apotheke seo, apotheken marketing, local seo apotheke, notdienst apotheke" },
  "local-seo-fahrschule": { titleDe: "Local SEO für Fahrschulen: Mehr Fahrschüler gewinnen", terms: "fahrschule seo, fahrschüler gewinnen, local seo fahrschule, führerschein marketing" },
  "local-seo-hochzeitsdienstleister": { titleDe: "Local SEO für Hochzeitsdienstleister: Florist bis DJ", terms: "hochzeitsdienstleister seo, hochzeit marketing, local seo hochzeit, wedding vendor seo" },
  "local-seo-umzugsunternehmen": { titleDe: "Local SEO für Umzugsunternehmen: In zwei Städten gefunden werden", terms: "local seo umzugsunternehmen, umzugsfirma kunden gewinnen, umzug google ranking, umzugsanfragen generieren, fernumzug marketing" },
  "local-seo-sprachschule": { titleDe: "Local SEO für Sprachschulen & Nachhilfe-Institute", terms: "sprachschule seo, nachhilfe marketing, local seo sprachschule, bildung seo" },
  "local-seo-baeckerei-konditorei": { titleDe: "Local SEO für Konditoreien & Tortenbetriebe: Spezialitäten vermarkten", terms: "konditorei seo, tortenbetrieb marketing, local seo konditorei, hochzeitstorte keywords" },
  "local-seo-cafe-coffeeshop": { titleDe: "Local SEO für Cafés & Coffee Shops", terms: "cafe seo, coffeeshop marketing, local seo cafe, kaffee seo" },
  "local-seo-hamburg": { titleDe: "Local SEO Hamburg: Der Hanseatische Marketing-Guide", terms: "local seo hamburg, seo hamburg, marketing hamburg, hamburger unternehmen" },
  "local-seo-frankfurt": { titleDe: "Local SEO Frankfurt: Finanzmetropole richtig nutzen", terms: "local seo frankfurt, seo frankfurt, marketing frankfurt, frankfurter unternehmen" },
  "local-seo-koeln": { titleDe: "Local SEO Köln: Rheinland-Marketing für lokale Unternehmen", terms: "local seo köln, seo köln, marketing köln, kölner unternehmen" },
  "local-seo-wien": { titleDe: "Local SEO Wien: Der Österreich-Guide für KMUs", terms: "local seo wien, seo wien, marketing wien, österreich seo" },
  "local-seo-stuttgart": { titleDe: "Local SEO Stuttgart: Automobilregion & mehr", terms: "local seo stuttgart, seo stuttgart, marketing stuttgart, schwaben seo" },
  "local-seo-duesseldorf": { titleDe: "Local SEO Düsseldorf: Mode, Messe & mehr Kunden", terms: "local seo düsseldorf, seo düsseldorf, marketing düsseldorf, nrw seo" },
  "local-seo-basel": { titleDe: "Local SEO Basel: Grenzregion Schweiz-Deutschland-Frankreich", terms: "local seo basel, seo basel, marketing basel, dreiländereck seo" },
  "technisches-local-seo-guide": { titleDe: "Technisches Local SEO: Der komplette Guide für lokale Unternehmen 2026", terms: "technical seo, technisches seo, localbusiness schema, schema markup, core web vitals" },
  "localbusiness-schema-implementierung": { titleDe: "LocalBusiness Schema implementieren: Komplette Anleitung mit Code-Beispielen", terms: "localbusiness schema, schema markup, json-ld, structured data, local seo schema" },
  "review-schema-implementierung": { titleDe: "Review Schema implementieren: Bewertungssterne in Google bekommen", terms: "review schema, aggregaterating, sterne google, rich snippets bewertungen, schema markup bewertungen" },
  "core-web-vitals-local-seo": { titleDe: "Core Web Vitals für lokale Websites: Performance-Guide", terms: "core web vitals, page speed, local seo performance, lcp fid cls" },
  "local-seo-voice-search": { titleDe: "Local SEO & Voice Search: Hey Google, wo ist...", terms: "voice search, sprachsuche, local seo voice, alexa siri google" },
  "google-posts-ranking-faktor": { titleDe: "Google Posts optimal nutzen: Der unterschätzte Ranking-Faktor", terms: "google posts, gbp posts, google business posts, lokale posts" },
  "lokale-landing-pages": { titleDe: "Lokale Landing Pages erstellen: One-Page pro Standort", terms: "lokale landing pages, standort seiten, geo landing pages, multi location seo" },
  "local-seo-tracking-kpis": { titleDe: "Local SEO Tracking: KPIs und Reporting richtig aufsetzen", terms: "local seo kpis, seo tracking, local seo reporting, google analytics lokal" },
  "local-seo-vs-organisch": { titleDe: "Local SEO vs. organisches SEO: Die wichtigsten Unterschiede", terms: "local seo vs seo, organische suche, local pack, seo unterschiede" },
  "google-maps-seo-vs-organic-seo": { titleDe: "Google Maps SEO vs. Organic SEO: Ranking-Faktoren, Strategien & ROI im Vergleich", terms: "google maps seo vs organic seo, maps ranking faktoren, organic seo vergleich, local pack vs organic, maps seo strategie" },
  "local-seo-berlin": { titleDe: "Local SEO Berlin: Der Hauptstadt-Guide für Unternehmen", terms: "local seo berlin, seo berlin, marketing berlin, berliner unternehmen" },
  "ki-tools-local-seo": { titleDe: "KI-Tools für Local SEO: Die besten AI-Helfer 2026", terms: "ki tools seo, ai local seo, chatgpt seo, künstliche intelligenz seo, ai marketing" },
  "google-ai-overviews-local-seo": { titleDe: "Google AI Overviews & Local SEO: Was sich ändert", terms: "google ai overviews, ai suche, sge local seo, google ki, generative search" },
  "seo-toolbox-kostenlose-ressourcen": { titleDe: "Die ultimative SEO-Toolbox: 50+ kostenlose Tools & Ressourcen", terms: "seo tools, kostenlose seo tools, seo toolbox, local seo tools, geo tools" },
  "gbp-fotos-optimieren": { titleDe: "Google Business Fotos optimieren: Der komplette Bilder-Guide", terms: "google business fotos, gbp bilder, google maps bilder, unternehmensfotos, foto optimierung" },
  "local-seo-mehrstufig-unternehmen": { titleDe: "Franchise-SEO Strategie: GBP-Management & Markenkonsistenz bei mehreren Standorten", terms: "franchise seo strategie, gbp management filialen, markenkonsistenz multi location, franchise google business" },
  "e-e-a-t-lokale-unternehmen": { titleDe: "E-E-A-T für lokale Unternehmen: Expertise beweisen & Vertrauen aufbauen", terms: "e-e-a-t, expertise, authority, trust, lokale autorität" },
  "lokale-seo-fuer-neugruender": { titleDe: "Local SEO für Neugründer: Von Null zur lokalen Sichtbarkeit", terms: "neugründer seo, startup local seo, existenzgründung, neue firma, lokales marketing startup" },
  "google-business-messaging": { titleDe: "Google Business Messaging: Kundenkommunikation optimal nutzen", terms: "google business messaging, gbp chat, kundenkommunikation, google chat, messaging einrichten" },
  "local-seo-physiotherapie": { titleDe: "Local SEO für Physiotherapie & Heilpraktiker: Patienten gewinnen", terms: "physiotherapie seo, heilpraktiker marketing, local seo therapie, patientengewinnung, wellness marketing" },
  "local-seo-notdienst-keywords": { titleDe: "Notdienst-Keywords: Wenn Kunden dringend suchen", terms: "notdienst seo, emergency keywords, sofort hilfe, 24 stunden service, dringende suche" },
  "google-business-kategorien-guide": { titleDe: "Google Business Kategorien: Welche passt zu deinem Unternehmen?", terms: "google business kategorien, gbp category, branchenkategorie, kategorie wählen, unternehmenskategorie" },
  "local-seo-zahnarzt": { titleDe: "Local SEO für Zahnärzte: Mehr Patienten durch Google", terms: "zahnarzt seo, dental marketing, local seo zahnarzt, patientengewinnung zahnarzt, zahnarztpraxis marketing" },
  "lokale-events-marketing": { titleDe: "Lokale Events für SEO nutzen: Sponsoring & Veranstaltungen", terms: "lokale events seo, sponsoring marketing, veranstaltungen, lokale autorität, event backlinks" },
  "google-business-produkte-services": { titleDe: "Google Business Produkte & Services optimal präsentieren", terms: "google business produkte, gbp services, produktkatalog, dienstleistungen präsentieren, preise google" },
  "local-seo-optiker": { titleDe: "Local SEO für Optiker & Hörakustiker: Kunden gewinnen", terms: "optiker seo, hörakustiker marketing, local seo optiker, brillen marketing, augenoptik seo" },
  "bewertungs-antworten-vorlagen": { titleDe: "Bewertungs-Antworten: 50 Vorlagen für jede Situation", terms: "bewertungen antworten, review response, antwort vorlagen, google rezensionen, kundenfeedback" },
  "local-seo-elektrotechnik": { titleDe: "Local SEO für Elektriker & Elektrotechniker: Mehr Aufträge", terms: "elektriker seo, elektrotechnik marketing, local seo elektriker, elektro notdienst, elektrofirma marketing" },
  "google-business-insights-verstehen": { titleDe: "Google Business Insights richtig verstehen & nutzen", terms: "google business insights, gbp analytics, statistiken verstehen, performance messen, google metriken" },
  "local-seo-maler-lackierer": { titleDe: "Local SEO für Maler & Lackierer: Mehr Aufträge gewinnen", terms: "maler seo, lackierer marketing, local seo maler, malerbetrieb marketing, renovierung seo" },
  "gbp-suspendiert-reaktivieren": { titleDe: "Google Business Profil suspendiert – So stellst du es wieder her (2026 Anleitung)", terms: "gbp suspendiert, google business suspendiert, profil reaktivieren, suspension beheben, google appeal" },
  "gbp-verifizierung-fehlgeschlagen": { titleDe: "Google Business Verifizierung schlägt fehl – 8 Lösungen für alle Probleme (2026)", terms: "gbp verifizierung, google verifizierung fehlgeschlagen, postkarte nicht erhalten, verifizierungscode, video verifizierung" },
  "duplicate-listing-entfernen": { titleDe: "Doppelte Google-Einträge löschen – Duplicate Listing Anleitung (2026)", terms: "duplicate listing, doppelte einträge, google business duplicate, duplicate entfernen, mehrere google einträge" },
  "gbp-bewertung-loeschen-anleitung": { titleDe: "Google Bewertung löschen lassen – Schritt-für-Schritt Anleitung (2026)", terms: "google bewertung löschen, fake bewertung melden, bewertung entfernen, negative bewertung löschen, google review löschen" },
  "ranking-ploetzlich-verschwunden": { titleDe: "Google Ranking plötzlich verschwunden – Ursachen & Soforthilfe (2026)", terms: "ranking verschwunden, google ranking weg, ranking einbruch, google penalty, ranking verloren" },
  "gbp-nicht-in-suche-sichtbar": { titleDe: "Google Business Profil nicht in Suche sichtbar – 12 Lösungen (2026)", terms: "gbp nicht sichtbar, google business nicht gefunden, profil nicht angezeigt, maps eintrag fehlt, gbp indexierung" },
  "gbp-mehrere-standorte": { titleDe: "Google Business für mehrere Standorte verwalten – Der Multi-Location Guide (2026)", terms: "gbp mehrere standorte, multi location seo, standortgruppen, bulk upload, filialisten google" },
  "gbp-oeffnungszeiten-sondertage": { titleDe: "Google Business Öffnungszeiten & Sondertage richtig einstellen (2026)", terms: "gbp öffnungszeiten, google business feiertage, sonderöffnungszeiten, betriebsferien eintragen, öffnungszeiten ändern" },
  "gbp-attribute-richtig-nutzen": { titleDe: "Google Business Attribute richtig nutzen – Alle Optionen erklärt (2026)", terms: "gbp attribute, google business attribute, barrierefreiheit, lgbtq freundlich, ausstattungsmerkmale" },
  "local-seo-vs-maps-seo": { titleDe: "Local SEO vs Maps SEO – Was ist der Unterschied? (2026)", terms: "local seo vs maps seo, unterschied local seo, google maps seo, lokale seo, maps optimierung" },
  "local-citations-2025": { titleDe: "Top-Verzeichnisse DACH 2026: Branchenspezifische Citation-Quellen nach Relevanz sortiert", terms: "top verzeichnisse dach, branchenbücher 2026, citation quellen, verzeichnis relevanz, nap einträge branche" },
  "local-seo-baeckerei": { titleDe: "Local SEO für Bäckereien: Mehr Kunden durch Google (2026)", terms: "bäckerei seo, bäcker local seo, bäckerei marketing, konditorei google, brot seo" },
  "local-seo-hannover": { titleDe: "Local SEO Hannover: Der Guide für niedersächsische Unternehmen", terms: "local seo hannover, seo hannover, marketing hannover, google ranking hannover, messe hannover seo" },
  "ai-search-optimization-2026": { titleDe: "AI Search Optimization 2026: So wirst du in der KI-Suche gefunden", terms: "ai search optimization, geo seo, ai overviews optimierung, chatgpt seo, generative engine optimization" },
  "ai-search-vs-traditional-search": { titleDe: "AI-Suche vs. Traditionelle Suche: Der komplette Vergleich für lokale Unternehmen", terms: "ai suche vs traditionelle suche, ai search vs traditional search, google ai overviews, zero click search, geo optimierung" },
  "seo-ferienwohnungen": { titleDe: "SEO für Ferienwohnungen: Schweiz, Bayern & Österreich – Raus aus der OTA-Falle", terms: "seo ferienwohnungen, ferienwohnung seo schweiz, vacation rental seo, direktbuchungen seo, google my business ferienwohnung" },
  "local-seo-reporting-template": { titleDe: "Local SEO Reporting Template: Monatlicher Report + KPI-Vorlage", terms: "local seo reporting, local seo report vorlage, local seo kpis, seo reporting template, google business report" },
  "google-business-profil-hub": { titleDe: "Google Business Profil Hub – Alle Guides & Anleitungen", terms: "google business profil, gbp optimierung, google my business guide, google business hub" },
  "local-seo-branchen-hub": { titleDe: "Local SEO Branchen-Guides – 22+ Branchen im Überblick", terms: "local seo branchen, branchen seo guide, local seo nach branche, branchenspezifisches seo" },
  "local-seo-staedte-hub": { titleDe: "Local SEO Städte-Guides – DACH-Region", terms: "local seo städte, local seo berlin, local seo münchen, local seo wien, städte seo guide" },
  "bewertungen-reputation-hub": { titleDe: "Bewertungen & Reputation Hub – Alle Guides", terms: "google bewertungen, bewertungen management, reputation management, review strategie, bewertungen hub" },
  "website-content-ai-suchmaschinen": { titleDe: "Website-Content für AI-Suchmaschinen strukturieren: Der komplette Guide", terms: "ai suchmaschinen, content struktur ai, geo optimierung, schema markup ai, llms.txt" },
  "local-seo-strategie-kleine-unternehmen": { titleDe: "Local SEO Strategie für kleine Unternehmen: Der komplette Aktionsplan 2026", terms: "local seo strategie, local seo kleine unternehmen, local seo kmu, lokale seo strategie, local seo aktionsplan" },
  "local-seo-ranking-faktoren-erklaert": { titleDe: "Local SEO Ranking-Faktoren erklärt: Alle Signale im Detail 2026", terms: "local seo ranking faktoren, lokale ranking faktoren, google local ranking, local pack ranking faktoren, local seo signale" },
  "ai-suche-lokale-unternehmen": { titleDe: "AI Search Optimization für lokale Unternehmen: Der komplette Guide 2026", terms: "ai search optimization, geo optimierung, ai suche lokale unternehmen, chatgpt local seo, google ai overviews local" },
  "local-link-building-blueprint": { titleDe: "Local Link Building Blueprint: Der komplette Leitfaden für lokale Backlinks 2026", terms: "local link building, lokale backlinks, lokales linkbuilding, ihk backlink, vereinssponsoring seo" },
  "local-seo-checkliste-komplett": { titleDe: "Local SEO Implementierungs-Checkliste: 80+ Maßnahmen in 8 Phasen systematisch umsetzen", terms: "local seo implementierung, local seo maßnahmen, lokale seo umsetzung, local seo schritt für schritt, seo implementierungsplan" },
  "google-maps-seo-hub": { titleDe: "Google Maps SEO Hub: Alle Guides für lokale Sichtbarkeit", terms: "google maps seo, google maps ranking, maps optimierung, google maps marketing, lokale sichtbarkeit google maps" },
  "wie-google-maps-ranking-funktioniert": { titleDe: "Google Maps Algorithmus erklärt: Nähe, Relevanz & Bekanntheit im Detail", terms: "google maps algorithmus, maps algorithmus erklärt, proximity relevance prominence, wie google maps funktioniert, local pack algorithmus" },
  "schema-strategie-dokument": { titleDe: "Schema-Strategie: Wann Article, FAQPage, HowTo & LocalBusiness einsetzen", terms: "schema strategie, structured data strategie, article schema, faqpage schema, howto schema" },
  "local-seo-statistiken-daten": { titleDe: "Local SEO Statistiken & Daten 2026: 88+ Datenpunkte für 22 Branchen", terms: "local seo statistiken, local seo daten, local seo benchmarks, ranking faktoren 2026, bewertungsstatistiken" },
  "faq-hub": { titleDe: "FAQ Hub: Alle Local SEO Fragen beantwortet", terms: "local seo faq, local seo fragen, google business profil faq, bewertungen faq, seo fragen antworten" },
  "faq-local-seo-grundlagen": { titleDe: "FAQ: Local SEO Grundlagen", terms: "local seo grundlagen faq, was ist local seo, local seo kosten, local seo dauer" },
  "faq-google-business-profil": { titleDe: "FAQ: Google Business Profil", terms: "google business profil faq, gbp fragen, google maps eintrag faq" },
  "faq-bewertungen-reputation": { titleDe: "FAQ: Bewertungen & Reputation", terms: "google bewertungen faq, bewertungen bekommen faq, negative bewertungen faq" },
  "faq-technisches-seo": { titleDe: "FAQ: Technisches SEO", terms: "technisches seo faq, schema markup faq, core web vitals faq, nap konsistenz faq" },
  "faq-ai-zukunft-local-seo": { titleDe: "FAQ: AI & Zukunft im Local SEO", terms: "ai local seo faq, google ai overviews faq, geo optimierung faq, voice search faq" },
  "faq-content-marketing-local-seo": { titleDe: "FAQ: Content & Marketing für Local SEO", terms: "local content marketing faq, lokales linkbuilding faq, citations faq" },
  "was-ist-geo-generative-engine-optimization": { titleDe: "Was ist GEO? Generative Engine Optimization erklärt", terms: "geo, generative engine optimization, ai seo, geo vs seo, ai search optimization" },
  "chatgpt-zitiert-lokale-unternehmen": { titleDe: "Wie zitiert ChatGPT lokale Unternehmen?", terms: "chatgpt local business, chatgpt citations, ai zitierfähigkeit, chatgpt seo, llm visibility" },
  "ai-visibility-index-local-seo-metrik": { titleDe: "AI Visibility Index – die neue Local-SEO-Metrik 2026", terms: "ai visibility index, ai sichtbarkeit messen, neue seo metriken, ai retrievability, geo metrics" },
  "schema-strategie-ai-retrieval": { titleDe: "Schema-Strategie für AI-Retrieval: So wirst du von LLMs gelesen", terms: "schema ai retrieval, jsonld llm, schema markup ai, ai friendly schema, geo schema" },
  "perplexity-claude-lokale-sichtbarkeit": { titleDe: "Perplexity & Claude für lokale Sichtbarkeit nutzen", terms: "perplexity local seo, claude ai seo, ai assistants local business, llm zitate, perplexity citations" },
  "chatgpt-search-lokale-unternehmen-2026": { titleDe: "ChatGPT Search für lokale Unternehmen 2026 — der komplette Optimierungs-Guide", terms: "chatgpt search, chatgpt search local seo, chatgpt search lokale unternehmen, openai search optimierung, oai-searchbot" },
  "apple-business-connect-local-seo-2026": { titleDe: "Apple Business Connect: Local SEO für Apple Maps & Siri 2026", terms: "apple business connect, apple maps seo, siri local seo, apple intelligence local seo, apple maps ranking" },
  "reddit-local-seo-ai-zitate-2026": { titleDe: "Reddit für Local SEO 2026: Wie du in ChatGPT- & Perplexity-Antworten zitiert wirst", terms: "reddit local seo, reddit ai zitate, reddit chatgpt zitiert, reddit perplexity, subreddit dach" },
  "google-ai-mode-local-seo-2026": { titleDe: "Google AI Mode 2026: Local SEO für Geminis konversationale Suche", terms: "google ai mode, ai mode local seo, gemini local seo, query fan-out, google ai mode dach" },
  "bing-copilot-local-seo-2026": { titleDe: "Bing & Microsoft Copilot 2026: Local SEO für ChatGPT, Edge & Windows", terms: "bing local seo, microsoft copilot seo, bing places, edge copilot local, bingbot robots txt" },
  "tiktok-search-local-seo-2026": { titleDe: "TikTok Search für Local SEO 2026: So wirst du von Gen Z gefunden", terms: "tiktok local seo, tiktok search, tiktok suchmaschine, gen z local search, tiktok ranking signale" },
  "voice-search-sprachassistenten-local-seo-2026": { titleDe: "Voice Search 2026: Local SEO für Alexa, Siri & Google Assistant", terms: "voice search local seo, alexa local seo, siri local seo, google assistant local, sprachsuche dach" },
  "ai-agents-lokale-buchungen-2026": { titleDe: "AI Agents 2026: Wie Operator, ChatGPT Agent & Gemini lokale Buchungen autonom erledigen", terms: "ai agents local seo, openai operator local, chatgpt agent buchung, gemini agent local, perplexity comet browser" },
  "geo-content-briefing-vorlage-2026": { titleDe: "GEO-Content-Briefing 2026: Vorlage für zitierfähige Texte in AI-Suche", terms: "geo content briefing, content briefing vorlage, ai suche content, zitierfaehige texte, answer block seo" },
  "ai-falschangaben-korrigieren-2026": { titleDe: "Falschangaben in AI-Antworten korrigieren 2026: 6-Schritte-Prozess", terms: "falsche angaben chatgpt unternehmen, ai halluzination firmendaten, nap fehler korrigieren, perplexity falsche oeffnungszeiten, unternehmensdaten bereinigen" },
  "unternehmensprofil-ki-funktionen-2026": { titleDe: "Unternehmensprofil & KI 2026: Welche Felder in AI-Antworten landen", terms: "google unternehmensprofil ki, gbp ai optimierung, profil kategorien leistungen, fragen und antworten profil, ai zusammenfassung lokal" },
  "local-seo-heizung-sanitaer": { titleDe: "Local SEO für Heizung & Sanitär (SHK): Notdienst und Projekte", terms: "local seo heizung sanitaer, shk betrieb marketing, klempner google ranking, notdienst seite handwerk, waermepumpe anfragen gewinnen" },
  "local-seo-gebaeudereinigung": { titleDe: "Local SEO für Gebäudereinigung: Objektanfragen statt Klicks", terms: "local seo gebaeudereinigung, reinigungsfirma kunden gewinnen, bueroreinigung anfragen, b2b local seo, unterhaltsreinigung marketing" },
  "local-seo-garten-landschaftsbau": { titleDe: "Local SEO für Garten- & Landschaftsbau: Saison richtig nutzen", terms: "local seo garten landschaftsbau, galabau kunden gewinnen, landschaftsgaertner google ranking, gartenpflege anfragen, gartengestaltung marketing" },
  "whatsapp-business-local-seo-2026": { titleDe: "WhatsApp Business für lokale Unternehmen 2026: Setup, NAP-Regeln & Recht", terms: "whatsapp business local seo, wa.me link website, whatsapp unternehmensprofil, nap konsistenz messenger, whatsapp datenschutz unternehmen" },
  "ai-crawler-steuern-gptbot-claudebot-2026": { titleDe: "AI-Crawler steuern 2026: GPTBot, ClaudeBot & PerplexityBot richtig konfigurieren", terms: "ai crawler steuern, gptbot robots.txt, claudebot blockieren, perplexitybot, google-extended" },
  "ai-zitat-monitoring-local-seo-2026": { titleDe: "AI-Zitat-Monitoring 2026: Erwähnungen in ChatGPT, Perplexity & Gemini messen", terms: "ai zitat monitoring, ai sichtbarkeit messen, chatgpt erwaehnungen tracken, perplexity monitoring, gemini local seo messung" },
  "llms-txt-lokale-unternehmen-2026": { titleDe: "llms.txt für lokale Unternehmen 2026: Setup, Beispiel & Best Practices", terms: "llms.txt, llms txt local seo, llms.txt beispiel, chatgpt zitate seo, perplexity crawler optimierung" },
};
